
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button buttonStart;
	private global::Gtk.Button buttonSettings;
	private global::Gtk.Button buttonInfo;
	private global::Gtk.Button buttonManual;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Button buttonCollectBackground;
	private global::Gtk.Button buttonScan;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView textviewOutput;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Statusbar statusbarSystemStatus;
	private global::Gtk.Statusbar statusbarTECTemp;
	private global::Gtk.Button buttonClearResults;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("M-PFQA");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.DefaultHeight = 600;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonStart = new global::Gtk.Button ();
		this.buttonStart.CanFocus = true;
		this.buttonStart.Name = "buttonStart";
		this.buttonStart.UseUnderline = true;
		this.buttonStart.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.hbox1.Add (this.buttonStart);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonStart]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonSettings = new global::Gtk.Button ();
		this.buttonSettings.CanFocus = true;
		this.buttonSettings.Name = "buttonSettings";
		this.buttonSettings.UseUnderline = true;
		this.buttonSettings.Label = global::Mono.Unix.Catalog.GetString ("Settings");
		this.hbox1.Add (this.buttonSettings);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonSettings]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonInfo = new global::Gtk.Button ();
		this.buttonInfo.CanFocus = true;
		this.buttonInfo.Name = "buttonInfo";
		this.buttonInfo.UseUnderline = true;
		this.buttonInfo.Label = global::Mono.Unix.Catalog.GetString ("Info");
		this.hbox1.Add (this.buttonInfo);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonInfo]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonManual = new global::Gtk.Button ();
		this.buttonManual.CanFocus = true;
		this.buttonManual.Name = "buttonManual";
		this.buttonManual.UseUnderline = true;
		this.buttonManual.Label = global::Mono.Unix.Catalog.GetString ("Manual Mode");
		this.hbox1.Add (this.buttonManual);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonManual]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.buttonCollectBackground = new global::Gtk.Button ();
		this.buttonCollectBackground.CanFocus = true;
		this.buttonCollectBackground.Name = "buttonCollectBackground";
		this.buttonCollectBackground.UseUnderline = true;
		this.buttonCollectBackground.Label = global::Mono.Unix.Catalog.GetString ("Collect Bkgnd");
		this.hbox4.Add (this.buttonCollectBackground);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.buttonCollectBackground]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.buttonScan = new global::Gtk.Button ();
		this.buttonScan.CanFocus = true;
		this.buttonScan.Name = "buttonScan";
		this.buttonScan.UseUnderline = true;
		this.buttonScan.Label = global::Mono.Unix.Catalog.GetString ("Collect Sample");
		this.hbox4.Add (this.buttonScan);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.buttonScan]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.textviewOutput = new global::Gtk.TextView ();
		this.textviewOutput.CanFocus = true;
		this.textviewOutput.Name = "textviewOutput";
		this.textviewOutput.Editable = false;
		this.GtkScrolledWindow.Add (this.textviewOutput);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w10.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.statusbarSystemStatus = new global::Gtk.Statusbar ();
		this.statusbarSystemStatus.Name = "statusbarSystemStatus";
		this.statusbarSystemStatus.Spacing = 6;
		this.statusbarSystemStatus.HasResizeGrip = false;
		this.hbox3.Add (this.statusbarSystemStatus);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.statusbarSystemStatus]));
		w11.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.statusbarTECTemp = new global::Gtk.Statusbar ();
		this.statusbarTECTemp.Name = "statusbarTECTemp";
		this.statusbarTECTemp.Spacing = 6;
		this.statusbarTECTemp.HasResizeGrip = false;
		this.hbox3.Add (this.statusbarTECTemp);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.statusbarTECTemp]));
		w12.Position = 1;
		// Container child hbox3.Gtk.Box+BoxChild
		this.buttonClearResults = new global::Gtk.Button ();
		this.buttonClearResults.CanFocus = true;
		this.buttonClearResults.Name = "buttonClearResults";
		this.buttonClearResults.UseUnderline = true;
		this.buttonClearResults.Label = global::Mono.Unix.Catalog.GetString ("Clear");
		this.hbox3.Add (this.buttonClearResults);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.buttonClearResults]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 427;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.DestroyEvent += new global::Gtk.DestroyEventHandler (this.OnDestroyEvent);
		this.buttonStart.Clicked += new global::System.EventHandler (this.OnButtonStartClicked);
		this.buttonSettings.Clicked += new global::System.EventHandler (this.OnButtonSettingsClicked);
		this.buttonInfo.Clicked += new global::System.EventHandler (this.OnButtonInfoClicked);
		this.buttonManual.Clicked += new global::System.EventHandler (this.OnButtonManualClicked);
		this.buttonCollectBackground.Clicked += new global::System.EventHandler (this.OnButtonCollectBackgroundClicked);
		this.buttonScan.Clicked += new global::System.EventHandler (this.OnButtonScanClicked);
		this.buttonClearResults.Clicked += new global::System.EventHandler (this.OnButtonClearResultsClicked);
	}
}
